# Generated by Django 3.2.6 on 2021-10-08 09:40

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Show', models.CharField(max_length=100)),
                ('Media', models.CharField(blank=True, choices=[('TV', 'TV'), ('Radio', 'Radio'), ('Youtube', 'Youtube'), ('Podcast', 'Podcast')], max_length=30, null=True)),
                ('Episode', models.IntegerField()),
                ('Date', models.DateField(max_length=100)),
                ('Time', models.TimeField()),
                ('Producer', models.CharField(max_length=100)),
                ('Producer_Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Artist', models.CharField(max_length=100)),
                ('Event', models.CharField(blank=True, choices=[('Festival', 'Festival'), ('Mini Tour', 'Mini Tour'), ('Corporate Event', 'Corporate Event'), ('Club Performance', 'Club Performance'), ('Paid Appearence', 'Paid Appearence')], max_length=100, null=True)),
                ('Name_of_Event', models.CharField(max_length=100)),
                ('Date', models.DateField(max_length=100)),
                ('Time_Slot', models.TimeField()),
                ('Set_Time', models.IntegerField()),
                ('Country', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Venue', models.CharField(max_length=100)),
                ('Promoter', models.CharField(max_length=100)),
                ('Promoter_Email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event', models.CharField(max_length=100)),
                ('Date', models.DateField(max_length=100)),
                ('Start_Time', models.TimeField()),
                ('Time_Slot', models.TimeField()),
                ('Country', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Venue', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Address_Line_1', models.CharField(max_length=300)),
                ('Address_Line_2', models.CharField(max_length=300)),
                ('Postcode', models.IntegerField()),
                ('State', models.CharField(max_length=100)),
                ('Area', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Country', models.CharField(max_length=300)),
                ('State_Region', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Spotify', models.URLField()),
                ('Apple_music', models.URLField()),
                ('Soundcloud', models.URLField()),
                ('Youtube', models.URLField()),
                ('Twitter', models.URLField()),
                ('Instagram', models.URLField()),
                ('Facebook', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Publicity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Media', models.CharField(blank=True, choices=[('Social Media', 'Social Media'), ('Magazine', 'Magazine'), ('Online Mag', 'Online Mag')], max_length=30, null=True)),
                ('Country', models.CharField(max_length=100)),
                ('Date', models.DateTimeField(max_length=100)),
                ('Link', models.URLField()),
            ],
        ),
    ]
