# Generated by Django 3.2.6 on 2021-08-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Show', models.CharField(max_length=100)),
                ('Media', models.CharField(blank=True, choices=[('TV', 'TV'), ('Radio', 'Radio'), ('Youtube', 'Youtube'), ('Podcast', 'Podcast')], max_length=30, null=True)),
                ('Episode', models.IntegerField()),
                ('Date', models.DateField(max_length=100)),
                ('Time', models.TimeField()),
                ('Producer', models.CharField(max_length=100)),
                ('Producer_Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
