# Generated by Django 3.2.6 on 2022-01-25 13:32

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amazon_Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Artist', models.CharField(max_length=100)),
                ('Song', models.CharField(max_length=100)),
                ('Duration', models.DurationField()),
                ('Plays', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Appear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Show', models.CharField(max_length=100)),
                ('Media', models.CharField(blank=True, choices=[('TV', 'TV'), ('Radio', 'Radio'), ('Youtube', 'Youtube'), ('Podcast', 'Podcast')], max_length=30, null=True)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Episode', models.IntegerField()),
                ('Producer', models.CharField(max_length=100)),
                ('Producer_Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Apple_music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Artist', models.CharField(max_length=100)),
                ('Song', models.CharField(max_length=100)),
                ('Duration', models.DurationField()),
                ('Plays', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Artist', models.CharField(max_length=100)),
                ('Event', models.CharField(blank=True, choices=[('Festival', 'Festival'), ('Mini Tour', 'Mini Tour'), ('Corporate Event', 'Corporate Event'), ('Club Performance', 'Club Performance'), ('Paid Appearence', 'Paid Appearence')], max_length=100, null=True)),
                ('Name_of_Event', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('Time_Slot', models.TimeField()),
                ('Country', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Venue', models.CharField(max_length=100)),
                ('Promoter', models.CharField(max_length=100)),
                ('Promoter_Email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Deezer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Artist', models.CharField(max_length=100)),
                ('Song', models.CharField(max_length=100)),
                ('Duration', models.DurationField()),
                ('Plays', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Facebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=None)),
                ('caption', models.TextField()),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('Comments', models.BigIntegerField()),
                ('Likes', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=None)),
                ('caption', models.TextField()),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('comments', models.BigIntegerField()),
                ('Likes', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('Start_Time', models.TimeField()),
                ('Time_Slot', models.TimeField()),
                ('Country', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Venue', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Stage_Name', models.CharField(max_length=100)),
                ('Phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Address_Line_1', models.CharField(max_length=300)),
                ('Address_Line_2', models.CharField(max_length=300)),
                ('Postcode', models.IntegerField()),
                ('State', models.CharField(max_length=100)),
                ('Area', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Country', models.CharField(max_length=300)),
                ('State_Region', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Spotify', models.URLField()),
                ('Apple_music', models.URLField()),
                ('Soundcloud', models.URLField()),
                ('Tidal', models.URLField()),
                ('Deezer', models.URLField()),
                ('Amazon_Music', models.URLField()),
                ('Youtube_music', models.URLField()),
                ('Youtube', models.URLField()),
                ('Twitter', models.URLField()),
                ('Instagram', models.URLField()),
                ('Tic_Tok', models.URLField()),
                ('Facebook', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Publicity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Media', models.CharField(blank=True, choices=[('Social Media', 'Social Media'), ('Magazine', 'Magazine'), ('Online Mag', 'Online Mag')], max_length=30, null=True)),
                ('Country', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('Link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Soundcloud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Artist', models.CharField(max_length=100)),
                ('Song', models.CharField(max_length=100)),
                ('Duration', models.DurationField()),
                ('Plays', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Spotify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Artist', models.CharField(max_length=100)),
                ('Song', models.CharField(max_length=100)),
                ('Duration', models.DurationField()),
                ('Plays', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tic_Tok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=None)),
                ('caption', models.TextField()),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('comments', models.BigIntegerField()),
                ('Likes', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TIDAL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Artist', models.CharField(max_length=100)),
                ('Song', models.CharField(max_length=100)),
                ('Duration', models.DurationField()),
                ('Plays', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Twitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tweet', models.TextField()),
                ('image', models.ImageField(upload_to=None)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('Replys', models.IntegerField()),
                ('Retweets', models.IntegerField()),
                ('Likes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Youtube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Artist', models.CharField(max_length=100)),
                ('Song', models.CharField(max_length=100)),
                ('Duration', models.DurationField()),
                ('Plays', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Youtube_music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Artist', models.CharField(max_length=100)),
                ('Song', models.CharField(max_length=100)),
                ('Duration', models.DurationField()),
                ('Plays', models.BigIntegerField()),
            ],
        ),
    ]
