# Generated by Django 3.2.6 on 2021-09-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event', models.CharField(max_length=100)),
                ('Date', models.DateField(max_length=100)),
                ('Start_Time', models.TimeField()),
                ('Time_Slot', models.TimeField()),
                ('Country', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Venue', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Publicity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Media', models.CharField(blank=True, choices=[('Social Media', 'Social Media'), ('Magazine', 'Magazine'), ('Online Mag', 'Online Mag')], max_length=30, null=True)),
                ('Country', models.CharField(max_length=100)),
                ('Date', models.DateTimeField(max_length=100)),
                ('Link', models.URLField()),
            ],
        ),
    ]
