# Generated by Django 3.2.6 on 2021-10-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine', '0002_performance_publicity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Address_Line_1', models.CharField(max_length=300)),
                ('Address_Line_2', models.CharField(max_length=300)),
                ('Postcode', models.IntegerField()),
                ('State', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Country', models.CharField(max_length=300)),
                ('State_Region', models.CharField(max_length=100)),
            ],
        ),
    ]
